### ISSUE TITLE
Starting server on Windows 10

### ISSUE THREAD

**Issue by TobiasMorell** [prozum/solitude#3]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Web.Cors, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  at at Microsoft.Owin.Cors.CorsOptions.get_AllowAll()
  at at Solitude.Server.Startup.ConfigureOAuth(IAppBuilder app) in c:\Users\Tobias Morell\Documents\GitHub\solitude\Solitude.Server\Startup.cs:line 79
  at at Solitude.Server.Startup.Configuration(IAppBuilder app) in c:\Users\Tobias Morell\Documents\GitHub\solitude\Solitude.Server\Startup.cs:line 29
  --- End of inner exception stack trace ---
  at at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
  at at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
  at at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
  at at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
  at at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
  at at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
  at at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
  at at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
  at at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
  at at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
  at at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
  at at Microsoft.Owin.Hosting.WebApp.Start[TStartup](String url)
  at at Solitude.Server.Program.Main(String[] args) in c:\Users\Tobias Morell\Documents\GitHub\solitude\Solitude.Server\Program.cs:line 18

**Comment by nimoov** [comment]
Try:
<dependentAssembly>
   <assemblyIdentity name="System.Web.Cors" publicKeyToken="31bf3856ad364e35" />
   <bindingRedirect oldVersion="1.0.0.0-5.0.0.0" newVersion="5.0.0.1" />
</dependentAssembly>

**Comment by nimoov** [comment]
Works with 601df41542bdd890a40d9ca78c4fa2dd70d120f6
